project:
  type: website

website:
  title: "20_ Quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

output:
  html:
    dir: docs

